### ISSUE TITLE
Otherwise

### ISSUE THREAD

**Issue by andersonnarciso** [speccode/acf-field-price#1]
Dude, thanks for the tool, just what I was needing. However, her result is 9,999.99 right? And to do where we changed 9.999,99?

**Comment by speccode** [comment]
For now you will have to use functions like `number_format` or other. Currently I'm on holiday but when I get back I can add field option to setup separators.

**Comment by andersonnarciso** [comment]
Sorry to bother you on your vacation :/ Number_format, I already use on the front end, but the interesting thing would be on the back end of the plugin, by the time the user is entering the price of "property" for example. It could just be a mask in time to fill the field, but he signs up only numbers.

Thanks for reply and thanks for plugin!

**Comment by badabingbreda** [comment]
Hi speccode, thanks for the extra ACF Field! But just like @andersonnarciso I'm looking to change the price format to 9.999,99 which is the standard in Europe. Any luck on making that addition?

**Comment by speccode** [comment]
Hello guys,
Sorry for such delay. I guess it's worth nothing but I updated plugin with new options. Now you can choose between predefined formats. Later you will be able to modify this list with `add_filter`. For now it should be enough I guess?

**Comment by andersonnarciso** [comment]
Mannnn! Very cool your modifications! Has a doubt emerged, it saves in the database with the format chosen? Or just numbers?

**Comment by speccode** [comment]
Got it. I'll fix it ASAP.

**Comment by speccode** [comment]
Fixed in last commit. Please let me know if there is any problem now.
